spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.108/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    com.imooc.LoggerTest: debug

wechat:
  # 公众账号，授权
  # 授权测试
  # mpAppId: wx26ec7b9d7d4b07ef
  # mpAppSecret: 8c6c0e1638bacd496d4d61265ea339ab
  # 借用
  mpAppId: wxd898fcb01713c658
  mpAppSecret: 29d8a650db31472aa87800e3b0d739f2
  # 支付/商户号
  mchId: 1483469312
  mchKey: 098F6BCD4621D373CADE4E832627B4F6
  # 发起支付不需要证书，退款需要
  KeyPath: /Users/mowen/Downloads/h5.p12
  notifyUrl: http://modawen.natapp1.cc/sell/pay/notify